------------------------------------------------
-------------- MEMBER 관련 테이블 --------------
------------------------------------------------
CREATE TABLE MEMBER ( 
	MEM_NO NUMBER,
	MEM_ID VARCHAR2(20) NOT NULL,
	MEM_PWD VARCHAR2(100) NOT NULL,
	MEM_NAME VARCHAR2(20) NOT NULL,
	MEM_PHONE VARCHAR2(20) NOT NULL,
    MEM_ZONECODE VARCHAR2(20) NOT NULL,
	MEM_ADDRESS VARCHAR2(200) NOT NULL,
    MEM_SUBADDRESS VARCHAR2(200) NOT NULL,
	MEM_EMAIL VARCHAR2(30) NOT NULL,
	MEM_REPORT NUMBER DEFAULT 0,
	MEM_ROLE VARCHAR2(20) DEFAULT 'ROLE_USER',
    MEM_POINT NUMBER DEFAULT 0,
	MEM_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(MEM_STATUS IN('Y', 'N')),
    MEM_ENROLLDATE DATE DEFAULT SYSDATE,
    MEM_PETYN VARCHAR2(1) DEFAULT 'N', 
    
    CONSTRAINT MEMBER_MEM_NO_PK PRIMARY KEY(MEM_NO),
    CONSTRAINT MEMBER_MEM_ID_UQ UNIQUE(MEM_ID)
);

COMMENT ON COLUMN MEMBER.MEM_NO IS '회원 번호';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEM_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '이름';
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '연락처';
COMMENT ON COLUMN MEMBER.MEM_ZONECODE IS '우편번호';
COMMENT ON COLUMN MEMBER.MEM_ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.MEM_SUBADDRESS IS '나머지주소';
COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEM_POINT IS '포인트';
COMMENT ON COLUMN MEMBER.MEM_REPORT IS '신고수';
COMMENT ON COLUMN MEMBER.MEM_ROLE IS '역할(ROLE_USER/ROLE_SELLER/ROLE_ADMIN)';
COMMENT ON COLUMN MEMBER.MEM_STATUS IS '회원 상태(Y/N)';
COMMENT ON COLUMN MEMBER.MEM_ENROLLDATE IS '가입일';
COMMENT ON COLUMN MEMBER.MEM_PETYN IS '반려동물 유무';

CREATE SEQUENCE SEQ_MEM_NO;

------------------------------------------------
-------------- SELLER 관련 테이블 --------------
------------------------------------------------

CREATE TABLE SELLER (
	SEL_NO NUMBER NOT NULL,
    MEM_NO NUMBER NOT NULL,
	SEL_NAME VARCHAR2(50) NOT NULL,
	SEL_LICENSE NUMBER	NOT NULL,
    
	CONSTRAINT SELLER_SEL_NO_PK PRIMARY KEY(SEL_NO),
	CONSTRAINT SELLER_MEM_NO_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON DELETE CASCADE
);


CREATE SEQUENCE SEQ_SEL_NO;

COMMENT ON COLUMN SELLER.SEL_NO IS '판매자 번호';
COMMENT ON COLUMN SELLER.MEM_NO IS '회원 번호';
COMMENT ON COLUMN SELLER.SEL_NAME IS '상점명';
COMMENT ON COLUMN SELLER.SEL_LICENSE IS '사업자 등록 번호';

------------------------------------------------
---------------- PET 관련 테이블 ---------------
------------------------------------------------

CREATE TABLE PET (
	PET_NO NUMBER NOT NULL,
	MEM_NO NUMBER NOT NULL,
	PET_NAME VARCHAR2(20) NULL,
	PET_TYPE VARCHAR2(1) NULL CHECK(PET_TYPE IN('D', 'C')),
    PET_WEIGHT VARCHAR2(1) NULL CHECK(PET_WEIGHT IN('S', 'M', 'L')),
	PET_INFO VARCHAR2(1000),
	PET_STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(PET_STATUS IN('Y', 'N')),
    
	CONSTRAINT PET_PET_NO_PK PRIMARY KEY(PET_NO),
	CONSTRAINT PET_MEM_NO_FK FOREIGN KEY(MEM_NO) REFERENCES MEMBER(MEM_NO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PET_NO;

COMMENT ON COLUMN PET.PET_NO IS '펫 번호';
COMMENT ON COLUMN PET.MEM_NO IS '회원 번호';
COMMENT ON COLUMN PET.PET_NAME IS '펫 이름';
COMMENT ON COLUMN PET.PET_INFO IS '펫 정보';
COMMENT ON COLUMN PET.PET_TYPE IS '펫 타입(D/C)';
COMMENT ON COLUMN PET.PET_WEIGHT IS '펫 몸무게(S/M/L)';
COMMENT ON COLUMN PET.PET_STATUS IS '펫 상태(Y/N)';

-------------------------------------
-- M_STATUS ='Y'인 일반 회원 전체 조회
SELECT M.MEM_NO,
       M.MEM_ID,
       M.MEM_PWD,
       M.MEM_NAME,
       M.MEM_PHONE,
       M.MEM_ZONECODE,
       M.MEM_ADDRESS,
       M.MEM_SUBADDRESS,
       M.MEM_EMAIL,
       M.MEM_POINT,
       M.MEM_REPORT,
       M.MEM_ROLE,
       M.MEM_STATUS,
       M.MEM_ENROLLDATE,
       M.MEM_PETYN,
       P.PET_NO,
       P.MEM_NO,
       P.PET_NAME,
       P.PET_INFO,
       P.PET_TYPE,
       P.PET_WEIGHT,
       P.PET_STATUS
FROM MEMBER M
INNER JOIN PET P ON (M.MEM_NO = P.MEM_NO)
WHERE M.MEM_STATUS ='Y';

SELECT * FROM PET;

-------------------------------------
-- 판매자 회원 전체 조회
SELECT M.MEM_NO,
       M.MEM_ID,
       M.MEM_PWD,
       M.MEM_NAME,
       M.MEM_PHONE,
       M.MEM_ZONECODE,
       M.MEM_ADDRESS,
       M.MEM_SUBADDRESS,
       M.MEM_EMAIL,
       M.MEM_POINT,
       M.MEM_REPORT,
       M.MEM_ROLE,
       M.MEM_STATUS,
       M.MEM_ENROLLDATE,   
       S.SEL_NO,
       S.SEL_NAME,
       S.SEL_LICENSE
FROM MEMBER M
INNER JOIN SELLER S ON (M.MEM_NO = S.SEL_NO);

COMMIT;

		SELECT M.MEM_NO,
		       M.MEM_ID,
		       M.MEM_PWD,
		       M.MEM_NAME,
		       M.MEM_PHONE,
		       M.MEM_ZONECODE,
		       M.MEM_ADDRESS,
		       M.MEM_SUBADDRESS,
		       M.MEM_EMAIL,
		       M.MEM_POINT,
		       M.MEM_REPORT,
		       M.MEM_ROLE,
		       M.MEM_STATUS,
		       M.MEM_ENROLLDATE,
		       P.PET_NO AS "P_PET_NO",
		       P.MEM_NO AS "P_MEM_NO",
		       P.PET_NAME AS "P_PET_NAME",
		       P.PET_INFO AS "P_PET_INFO",
		       P.PET_TYPE AS "P_PET_TYPE",
		       P.PET_WEIGHT AS "P_PET_WEIGHT",
		       P.PET_STATUS AS "P_PET_STATUS"
		FROM MEMBER M
		INNER JOIN PET P ON (M.MEM_NO = P.MEM_NO)
		WHERE M.MEM_ID = 'admin' AND M.MEM_STATUS ='Y';


		SELECT COUNT(*) 
		FROM MEMBER 
		WHERE MEM_ID = 'admin' AND MEM_STATUS ='Y';
        
DROP TABLE MEMBER;
DROP TABLE PET;
DROP TABLE SELLER;