-- 일반 회원
CREATE TABLE USER (
	USER_NO	NUMBER NOT NULL,
    USER_ID	VARCHAR2(20) NOT NULL,
	USER_PWD VARCHAR2(50) NOT NULL,
    USER_NAME VARCHAR2(20) NOT NULL,
    USER_PHONE VARCHAR2(20) NOT NULL,
    USER_ZONECODE NUMBER NULL,
	USER_ADDRESS VARCHAR2(200) NULL,
    USER_SUBADDRESS VARCHAR2(200) NULL,
	USER_EMAIL VARCHAR2(30) NOT NULL,
	USER_POINT NUMBER NULL DEFAULT '0',
	USER_ROLE VARCHAR2(10) NOT NULL DEFAULT '일반' COMMENT '판매자/관리자/일반',
	USER_STATUS	VARCHAR2(1)	NOT NULL DEFAULT 'Y',
	USER_REPORT	NUMBER NULL DEFAULT '0',
    USER_ENROLLDATE DATE NOT NULL DEFAULT SYSDATE,   
    
    CONSTRAINT USER_NO_PK PRIMARY KEY(USER_NO),
    CONSTRAINT USER_USER_ID UNIQUE(USER_ID),
    CONSTRAINT USER_USER_EMAIL UNIQUE(USER_EMAIL)

);

CREATE SEQUENCE SEQ_USER_NO;


COMMENT ON COLUMNE USER.USER_NO IS '회원번호';
COMMENT ON COLUMNE USER.USER_ID IS '아이디';
COMMENT ON COLUMNE USER.USER_PWD IS '비밀번호' ;
COMMENT ON COLUMNE USER.USER_NAME IS '이름' ;
COMMENT ON COLUMNE USER.USER_PHONE IS '핸드폰번호' ;
COMMENT ON COLUMNE USER.USER_ZONECODE IS '우편번호' ;
COMMENT ON COLUMNE USER.USER_ADDRESS IS '주소' ;
COMMENT ON COLUMNE USER.USER_SUBADDRESS IS '나머지주소' ;
COMMENT ON COLUMNE USER.USER_EMAIL IS '이메일' ;
COMMENT ON COLUMNE USER.USER_POINT IS '포인트' ;
COMMENT ON COLUMNE USER.USER_ROLE IS '역할';
COMMENT ON COLUMNE USER.USER_STATUS IS '상태값';
COMMENT ON COLUMNE USER.USER_REPORT IS '경고횟수';

-- 반려동물
CREATE TABLE PET (
    USER_NO	NUMBER NOT NULL
    PET_NO NUMBER NULL,
    PET_PETNAME VARCHAR2(20) NULL,
    PET_PETTYPE VARCHAR2(20) NULL CHECK(USER_PETTYPE IN('강아지', '고양이')),
    PET_PETWEIGHT VARCHAR2(20) NULL CHECK(USER_WEIGHT IN('소', '중', '대')),
    PET_PETINFO VARCHAR2(200) NULL
    PET_STATUS VARCHAR2(1) NULL DEFAULT 'Y'

    CONSTRAINT PET_USER_NO_FK FOREIGN KEY(USER_NO) REFERENCE USER(USER_NO) ON DELETE SET NULL,
    CONSTRAINT PET_PET_NO PRIMARY KET(PET_NO)
);

CREATE SEQUENCE SEQ_PET_NO;

COMMENT ON COLUMNE PET.PET_NO IS '펫 번호';
COMMENT ON COLUMNE PET.PET_PETNAME IS '펫 이름';
COMMENT ON COLUMNE PET.PET_PETTYPE IS '펫 타입';
COMMENT ON COLUMNE PET.PET_PETWEIGHT IS '펫 무게';
COMMENT ON COLUMNE PET.PET_PETINFO IS '펫 특징';
COMMENT ON COLUMNE PET.PET_STATUS IS '펫 상태';

-- 판매자 회원
CREATE TABLE SELLER (
	SELLER_NO NUMBER NOT NULL,
    SHOP_NAME VARCHAR2(50) NOT NULL
    SHOP_LICENSE NUMBER NOT NULL,
    
    CONSTRAINT SELLER_SELLER_NO FOREIGN KEY(SELLER_NO) REFERENCE USER(USER_NO) ON DELETE SET NULL
);

COMMENT ON COLUMNE SELLER.SELLER_NO IS '판매자 번호';
COMMENT ON COLUMNE SELLER.SHOP_NAME IS '상호명';
COMMENT ON COLUMNE SELLER.SHOP_LICENSE IS '사업자번호';

